### PR TITLE
Implemented keys style

### PR DESCRIPTION
**Pull request by riccardoflp**
Not breaking changes and backwards compatible.

Implented the possibility to change keys style. 

The style can be chosen with the `keys_style` configuration (default style is selected).

### Default configuration with `keys_style: base`:
default_base_keys_style

### Custom configuration omitting `keys_style`
default_keys_style

### Custom configuration with `keys_style: base`
base_keys_style

### New draw configurations in config.py
``` py
    # relative position of key legend
    legend_rel_x: float = 0
    legend_rel_y: float = 0

    # change key style: default, base
    keys_style: str = 'default'

    # relative position of external key rectangle
    key_base_tile_rel_x: float = 0
    key_base_tile_rel_y: float = -2.5
    # relative dimension of internal key rectangles
    key_base_tile_rel_w: float = -12
    key_base_tile_rel_h: float = -12
    # curvature of rounded internal key rectangles
    key_base_tile_rx: float = 4.5
    key_base_tile_ry: float = 4.5
```
#### svg_style
``` css
        /* default key background styling  */
        rect.key-background, rect.held-background, rect.ghost-background {
            fill: black
        }

        /* default key styling */
        rect.key, rect.key-side {
            fill: #f6f8fa;
            stroke: #c9cccf;
            stroke-width: 1;
        }

        /* default key side styling */
        rect.key-side, rect.held-side, rect.ghost-side {
            opacity: 0.9;
        }
```

### CODE REVIEW

**Comment by riccardoflp** [comment]
If you want to see the custom configuration, you can find them here [Rickyria](https://gitlab.com/riccardo.filippozzi/rickyria/-/tree/new_keymap?ref_type=heads) into [keymap_drawer_config.yaml](https://gitlab.com/riccardo.filippozzi/rickyria/-/blob/new_keymap/keymap_drawer_config.yaml)

**Comment by caksoylar** [comment]
This is very cool, thank you! I am reviewing the code and playing around with it. I have some things in mind that I'd do differently regarding config organization and code but I might not bother you with them and instead do some refactoring on top of your implementation.

There are two main things I have in mind and would like your input on:
1. I don't love the name `keys_style: base`. Both keys and style are pretty overloaded. What this styling is doing is essentially adding "profile" (in [KLE](http://www.keyboard-layout-editor.com) terms, which I assume is what you were inspired from) using some additional shading to the sides.
  We could call it `key_profile: base` which would allow for additional profile types. However it seems to me that different profiles can be implemented by changing the new parameters you added anyway. So I am leaning towards a simple `draw_key_sides: true` and naming the parameters `key_side.rel_x` etc.
2. I don't really like that the outer key dimensions shrink when you use `keys_style: base`. Nothing jumps out to me in the default config that causes it and I haven't looked into the drawing code enough to see why this happens. Can we fix this so that by default the key dims and gaps between keys will be the same as `keys_style: default`?

**Comment by riccardoflp** [comment]
1. Ok, I agree with you on remove `keys_style`, change the names and group parameters. I will use the names that you have suggest.
2. I think that is only due to my yaml configurations, what you will get with the `draw_key_sides: true` is showed in the first image. Also my variables name and my comments misleading you from what my implementation really do.

I'm cleaning up everything ;)

**Comment by riccardoflp** [comment]
@caksoylar ok, I cleaned up names and comments. Take a look. Thanks :)

**Comment by caksoylar** [comment]
The new config looks good, thanks :+1:

This change seems to change the default styling as well, without setting any parameters. Can you fix that? I would also like to keep the same key outlines for `draw_key_sides: true`, like I mentioned before quoted below:

> 2. I don't really like that the outer key dimensions shrink when you use `keys_style: base`. Nothing jumps out to me in the default config that causes it and I haven't looked into the drawing code enough to see why this happens. Can we fix this so that by default the key dims and gaps between keys will be the same as `keys_style: default`?

I hope if you fix the default styling then this will be fixed as well. For reference, this is the `main` branch render 
`keymap draw examples/showcase.yaml >showcase.main.svg`:
image

This is your changes merged to main `keymap draw examples/showcase.yaml >showcase.sides.svg`:
image

**Comment by riccardoflp** [comment]
@caksoylar, sorry the issue was my oversight.

**Comment by caksoylar** [comment]
Thank you for your contribution! I refactored it a bit, changed some names and converted the "background rect+opacity" approach to a CSS brightness filter. I also swapped the signs of key side parameters. Please let me know if you have any trouble with any of the changes.

**Pull request closed without merging**
