### PR TITLE
Add Docker image for the CLI

### PR DESCRIPTION
**Pull request by hnaderi**
Hi, Thanks for this great tool!
This PR adds a docker image that is automatically published to the GitHub container registry for `tags` and pushes on `main`.
Having a docker image for the CLI would make it easier to use the CLI in the CI/CD and on other platforms.

### CODE REVIEW

**Comment by caksoylar** [comment]
Hi, thanks for the nice words and the PR!

Can I ask why you use the Docker container, for example over the `pip` installation on your OS? I try to keep the installation simple and not very intrusive to your system (e.g. if you use `pipx`), and I feel like a Docker image might be overkill for this application. But I am open to changing my mind and I'd be interested to learn why others might prefer using a container.

**Comment by hnaderi** [comment]
The main use case would be on CI pipelines, where the containers are often used as an environment (it was my use case in the first place).
Using pipx is also really easy but requires extra packaging on immutable OSes like NixOS and Guix.

However, given the fact that it might be a niche use case and not the common use case I also think it might be overkill and I'm completely fine if you think it should be out of the scope of this project.

**Comment by caksoylar** [comment]
Thanks for the response, I admittedly am not familiar with Nix/Guix and limitations if `pip install`ing in them. I think I'd rather not maintain it and I appreciate you understanding.

If you let me know a stable path I can point to (like your fork's `main`) I will add a pointer to the Dockerfile in the community section of the README, in case this is useful to anyone else.

**Comment by hnaderi** [comment]
Sure, I changed the [README](https://github.com/hnaderi/keymap-drawer/tree/main#using-docker) in my fork to have the address of the container image in my container registry on GitHub.
I'll close this one, thanks for the time @caksoylar  :blush:

**Pull request closed without merging**
