### PR TITLE
Added kyria rev2 qmk layout

### PR DESCRIPTION
**Pull request by riccardoflp**

### CODE REVIEW

**Comment by riccardoflp** [comment]
Example:
rickyria

**Comment by caksoylar** [comment]
Hey, thanks for the PR. A few remarks/fixes to make:
- You should remove `matrix` fields from the layout
- You should make sure the layout macro matches QMK layouts, i.e. [`LAYOUT_split_3x6_5`](https://config.qmk.fm/#/splitkb/kyria/rev1/LAYOUT_split_3x6_5) instead of `LAYOUT`
  - Ideally we'd add also `LAYOUT_split_3x5_5` without the outer pinky column since some revisions support removing those
- The layout is a bit off on the rotated thumbs. Can you use the `rx, ry` coordinates and `r` values from [the official KLE](https://docs.splitkb.com/hc/en-us/articles/360010818820-Is-there-a-Keyboard-Layout-Editor-template-available-for-the-Kyria-)? This should make it so that the top and bottom thumb keys are nicely parallel
- We should name it `kyria_rotated.json`, since that's the convention we are going with layouts that deviate from QMK defaults (see `corne_rotated`, `sofle_rotated` etc.)
  - Then we can assign it to be the [default value for the ZMK shields](https://github.com/caksoylar/keymap-drawer/blob/main/resources/zmk_keyboard_layouts.yaml#L113) and QMK users that don't mind it differing from QMK Configurator can override manually.

**Comment by micampe** [comment]
Hello, this hasn't been updated in a while, so I ported the rotated layout from the KLE coordinates. Attaching the file below.
[splitkb@kyria_rotated.json](https://github.com/caksoylar/keymap-drawer/files/14775171/splitkb%40kyria_rotated.json)

**Comment by caksoylar** [comment]
Thanks @micampe, committed it as `kyria_rotated` for now. I am planning to introduce an additional mapping layer soon so that all QMK keyboards like `splitkb/kyria/rev1` resolve to use `kyria_rotated.json`.

**Comment by caksoylar** [comment]
Added the mapping layer in e20025a so that e.g. `splitkb/kyria/rev2` will pick up `kyria_rotated` file.

**Pull request closed without merging**
